### ISSUE TITLE
IndentationError in BigSMILES_homopolymer.py

### ISSUE THREAD

**Issue by onecoinbuybus** [CDAL-SChoi/BigSMILES_homopolymer#2] opened 2024-06-08 14:27 UTC
Description:
There is an error occurred: IndentationError: expected an indented block after 'if' statement on line 280

Before Fix:
```
                if not_large_x:
                    if not_large_x:
                tmp = tmp[:large_x] + tmp[large_x:small_x] + tmp[not_large_x:not_large_y+1] + tmp[small_x] + tmp[not_large_y + 1:large_y] + tmp[
```
After Fix:
```
                if not_large_x:
                    # if not_large_x:
                    tmp = tmp[:large_x] + tmp[large_x:small_x] + tmp[not_large_x:not_large_y+1] + tmp[small_x] + tmp[not_large_y + 1:large_y] + tmp[
                                                                                                small_y] + tmp[small_x + 1:small_y] + tmp[large_y:]        ## changed in ver 1.0.5
```
Thank you for your attention.

**Comment by CDAL-SChoi** [comment] 2024-06-09 14:35
Apologies for the inconvenience caused by the incorrect modifications in version 1.0.5.
Regretfully, the failure to double-check the update has resulted in this inconvenience.

Version 1.0.6, which includes corrections for the identified syntax errors, will be released.

Thank you very much for your interest in our project and for identifying the issue!

**Closed as completed by CDAL-SChoi** 2024-06-09 14:35 UTC
